import 'dart:async';
import 'package:after_layout/after_layout.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:student_portal/admin/providers/student_fee_detail_provider.dart';
import 'package:student_portal/admin/screens/fee/student_fee_status_detail_screen.dart';
import 'package:student_portal/shared/configs/theme/app_colors.dart';
import 'package:student_portal/shared/configs/theme/custom_text_styles.dart';
import 'package:student_portal/shared/get_it.dart';
import 'package:student_portal/shared/utils/common.dart';
import 'package:student_portal/student/models/core/challan_detail.dart';

class StudentFeeStatusScreen extends StatefulWidget {
  const StudentFeeStatusScreen({super.key, required this.regNo});
  final String regNo;
  @override
  State<StudentFeeStatusScreen> createState() => _FeeStatusState();
}

class _FeeStatusState extends State<StudentFeeStatusScreen>
    with AfterLayoutMixin {
  @override
  FutureOr<void> afterFirstLayout(BuildContext context) {
    final provider = getIt<StudentFeeDetailProvider>();
    provider.getFeeStatus(widget.regNo);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Fee Status"),
      ),
      body: Consumer<StudentFeeDetailProvider>(builder: (context, provider, _) {
        if (provider.cList == null) {
          return const Center(
            child: CircularProgressIndicator(),
          );
        }
        if (provider.cList!.isEmpty) {
          return const Center(
            child: Text("Challan not yet generated by the student"),
          );
        }
        return ListView.builder(
            padding: const EdgeInsets.all(8),
            itemCount: provider.cList!.length,
            itemBuilder: (context, index) {
              return _InstallmentCard(
                model: provider.cList![index],
              );
            });
      }),
    );
  }
}

class _InstallmentCard extends StatefulWidget {
  const _InstallmentCard({required this.model});
  final ChallanDetail model;

  @override
  State<_InstallmentCard> createState() => _InstallmentCardState();
}

class _InstallmentCardState extends State<_InstallmentCard> {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () async {
        await navigate(
            context, StudentFeeStatusDetailScreen(model: widget.model));
        setState(() {});
      },
      child: Card(
          elevation: 3,
          child: ListTile(
            title: Text('Installment No ${widget.model.installmentNo}'),
            subtitle: Text('${widget.model.amount} RS'),
            trailing: Text(
              widget.model.status ? "Done" : "Pending",
              style: boldTextStyle.copyWith(
                  color: widget.model.status ? primaryColor : Colors.red),
            ),
          )),
    );
  }
}
